### PR TITLE
Update content, fix links

### PR DESCRIPTION
**Pull request by kelreel**

### CODE REVIEW

**Comment by bydemir1** [comment]
lets

**Comment by shivsantosh1996** [comment]
I unable to join discord . Kindly resolve my issue.
photo1709465575 (1)
photo1709465575
photo1709496887

**Comment by shivsantosh1996** [comment]
@getairdrop24    I have already tried many times. But still unable to join.

**Comment by shivsantosh1996** [comment]
@getairdrop24  , No i unable to join discord channel.

**Comment by shivsantosh1996** [comment]
@getairdrop24 Kindly help me to resolve my issue. Thanks in advance.

**Comment by shivsantosh1996** [comment]
@getairdrop24  I tried this also, but unable to resolve my issue. Kindly look error into screenshot.

zk3

**Comment by shivsantosh1996** [comment]
@getairdrop24  Hello mate kindly resolve my issue.

**Comment by shivsantosh1996** [comment]
@MexicanAce   ,   I unable to join discord . Kindly resolve my issue. I tried many times, but unable to resolve my issue. Kindly look error into screenshot.

zk1
zk2
zk3

**Comment by bydemir1** [comment]
nice post

**Pull request closed without merging**
